version: "3.9"
services:
  db:
    image: postgres:16.3
    ports:
      - "5432:5432"
    networks:
      - sponsorshipNetwork
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=product-reviews

  api:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DATABASE_CONNECTION_URL=postgresql://user:password@db:5432/product-reviews?sslmode=disable