// Code generated by mockery v2.43.2. DO NOT EDIT.

package mock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	service "github.com/victorhsb/review-bot/backend/service"

	uuid "github.com/google/uuid"
)

// MessageStorage is an autogenerated mock type for the MessageStorage type
type MessageStorage struct {
	mock.Mock
}

type MessageStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MessageStorage) EXPECT() *MessageStorage_Expecter {
	return &MessageStorage_Expecter{mock: &_m.Mock}
}

// ListMessagesByParticipant provides a mock function with given fields: _a0, _a1
func (_m *MessageStorage) ListMessagesByParticipant(_a0 context.Context, _a1 uuid.UUID) ([]service.Message, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ListMessagesByParticipant")
	}

	var r0 []service.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]service.Message, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []service.Message); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MessageStorage_ListMessagesByParticipant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMessagesByParticipant'
type MessageStorage_ListMessagesByParticipant_Call struct {
	*mock.Call
}

// ListMessagesByParticipant is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
func (_e *MessageStorage_Expecter) ListMessagesByParticipant(_a0 interface{}, _a1 interface{}) *MessageStorage_ListMessagesByParticipant_Call {
	return &MessageStorage_ListMessagesByParticipant_Call{Call: _e.mock.On("ListMessagesByParticipant", _a0, _a1)}
}

func (_c *MessageStorage_ListMessagesByParticipant_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID)) *MessageStorage_ListMessagesByParticipant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MessageStorage_ListMessagesByParticipant_Call) Return(_a0 []service.Message, _a1 error) *MessageStorage_ListMessagesByParticipant_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MessageStorage_ListMessagesByParticipant_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]service.Message, error)) *MessageStorage_ListMessagesByParticipant_Call {
	_c.Call.Return(run)
	return _c
}

// SaveMessage provides a mock function with given fields: _a0, _a1
func (_m *MessageStorage) SaveMessage(_a0 context.Context, _a1 service.Message) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for SaveMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, service.Message) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MessageStorage_SaveMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveMessage'
type MessageStorage_SaveMessage_Call struct {
	*mock.Call
}

// SaveMessage is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 service.Message
func (_e *MessageStorage_Expecter) SaveMessage(_a0 interface{}, _a1 interface{}) *MessageStorage_SaveMessage_Call {
	return &MessageStorage_SaveMessage_Call{Call: _e.mock.On("SaveMessage", _a0, _a1)}
}

func (_c *MessageStorage_SaveMessage_Call) Run(run func(_a0 context.Context, _a1 service.Message)) *MessageStorage_SaveMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(service.Message))
	})
	return _c
}

func (_c *MessageStorage_SaveMessage_Call) Return(_a0 error) *MessageStorage_SaveMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MessageStorage_SaveMessage_Call) RunAndReturn(run func(context.Context, service.Message) error) *MessageStorage_SaveMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMessageStorage creates a new instance of MessageStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessageStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessageStorage {
	mock := &MessageStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
