// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Message struct {
	ID         uuid.UUID
	ReceiverID *uuid.UUID
	SenderID   *uuid.UUID
	Message    string
	CreatedAt  pgtype.Timestamptz
}

type Product struct {
	ID        uuid.UUID
	Title     string
	CreatedAt pgtype.Timestamptz
}

type ProductReview struct {
	ID        uuid.UUID
	ProductID uuid.UUID
	Rating    pgtype.Int4
	Sentiment pgtype.Int4
	Comment   pgtype.Text
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID        uuid.UUID
	Username  string
	CreatedAt pgtype.Timestamptz
}
